# Generated by Django 3.0.7 on 2020-08-12 07:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200812_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('url', models.CharField(max_length=512, verbose_name='图片地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False, verbose_name='主键id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('tag', models.CharField(max_length=64, verbose_name='标签')),
                ('up', models.CharField(max_length=64, verbose_name='作者')),
                ('views', models.IntegerField(default=0, null=True, verbose_name='当前打卡天数')),
                ('content', tinymce.models.HTMLField()),
                ('images', models.ManyToManyField(to='app.Img', verbose_name='新闻封面')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
