# Generated by Django 3.0.7 on 2020-08-12 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200812_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='是否上线'),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, null=True, verbose_name='阅读量'),
        ),
    ]
